trigger:
  branches:
    include:
      - main  # Ou a branch que deseja monitorar

pool:
  vmImage: 'ubuntu-latest'  # Você pode mudar para 'windows-latest' ou 'macOS-latest' se necessário

steps:
# Instalar a versão do Node.js
- task: NodeTool@0
  inputs:
    versionSpec: '14.x'  # Aqui você define a versão do Node.js necessária para o projeto
  displayName: 'Instalar Node.js'

# Instalar dependências do projeto (incluindo Cypress)
- script: |
    npm install
  displayName: 'Instalar dependências'

# Rodar os testes do Cypress
- script: |
    npx cypress run
  displayName: 'Rodar testes do Cypress'
