trigger:
  branches:
    include:
      - Atualizações  # Ou a branch que deseja monitorar

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '16.x'
  displayName: 'Use Node.js'

- script: |
    echo "Listing files in the current directory"
    ls -la
  displayName: 'Lista os arquivos que estão na pasta'

- script: |
    npm install
    npm install cypress --save-dev
  displayName: 'Instalar dependências e o Cypress'

- script: npx cypress run
  displayName: 'Roda os testes do Cypress'
