# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: UseNode@2
  inputs:
    versionSpec: '14.x'  # ou qualquer versão do Node.js


- script: |
    npm install
    npx cypress run
  displayName: 'Install dependencies and run Cypress tests'