trigger:
  branches:
    include:
      - main  # Ou a branch que deseja monitorar

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '16.x'
  displayName: 'Use Node.js'

- script: npm install
  displayName: 'Install dependencies'

- script: npm install cypress --save-dev
  displayName: 'Install Cypress'

- script: npx cypress run
  displayName: 'Run Cypress Tests'
