trigger:
  branches:
    include:
      - Atualizações  # Ou a branch que deseja monitorar

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '16.x'
  displayName: 'Use Node.js'

- script: |
    echo "Listing files in the current directory"
    ls -la
  displayName: 'List Current Directory'

- script: |
    npm install
    npm install cypress --save-dev
  displayName: 'Install dependencies and Cypress'

- script: npx cypress run
  displayName: 'Run Cypress Tests'

- script: npx cypress --version
  displayName: 'Verify Cypress Installation'
